### ISSUE TITLE
License

### ISSUE THREAD

**Issue by numb3r23** [Arahnoid/UVChecker-map#1]
Love the textures, many thanks for sharing! 

Could you attach a license to the repo to clarify under which circumstances they can be used? I know it says "free" but having a definitive/official one attached to it would help in distributing it.

A starting point could be http://creativecommons.org/choose/

**Comment by Arahnoid** [comment]
Added license. Looks like this one have no restriction and is free for everyone free for any use :smiley: 

<p xmlns:dct="http://purl.org/dc/terms/">
<a rel="license" href="http://creativecommons.org/publicdomain/mark/1.0/">
<img src="http://i.creativecommons.org/p/mark/1.0/88x31.png"
     style="border-style: none;" alt="Public Domain Mark" />
</a>
<br />
This work (<span property="dct:title">UVChecker-map</span>, by <a href="https://github.com/Arahnoid/UVChecker-map/issues/1" rel="dct:creator"><span property="dct:title">Igor Grinchesku</span></a>) is free of known copyright restrictions.
</p>
